name       : miller
version    : 5.1.0
release    : 2
source     :
    - https://github.com/johnkerl/miller/archive/v5.1.0.tar.gz : 07a498c0228e15321798e5f3f6d03ee6ba9aaf13110f55e52ddfadee52b9da6a
license    : BSD-2-Clause
component  : programming.tools
summary    : Miller is like awk, sed, cut, join, and sort for name-indexed data such as CSV, TSV, and tabular JSON
description: |
    Miller is like awk, sed, cut, join, and sort for name-indexed data such as CSV, TSV, and tabular JSON
setup      : |
    %reconfigure
build      : |
    %make
install    : |
    %make_install
